### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by smuth4**
Uses Debian in order to align build and run images on the same supported platform. Note that `GLUSTER_VERSION` must be set to a number rather than LATEST due to http://download.gluster.org/pub/gluster/glusterfs/LATEST/rsa.pub being a 404 as well as differences in directory structure.
I also noticed that despite 567cf6d017b4c91f7faf2e68b36ed3f2616169f8 removing gometalinter, the `scripts/` directory was never touched, so it's still required to be installed for the make commands to work.

### CODE REVIEW

**Comment by aravindavk** [comment]
Thanks for pointing to gometalinter issue in scripts directory. I will send PR to address that issue.

**Comment by aravindavk** [comment]
Please move the Dockerfile to extras directory. May be with name `debian.Dockerfile`

**Comment by adampl** [comment]
Hi, how to run this container to make it work with a Gluster cluster?

I asked in #73 but now I see you created your own image, but the issue remains unresolved.

**Comment by smuth4** [comment]
I am unable to reproduce this on the latest code, and it's odd that it would allow adding/updating the repo but bail on the actual package repo. Is it consistent? If not, it might be related to https://bugs.launchpad.net/ubuntu/+source/gnutls26/+bug/1111882, if so, you may want to double check your network's setting,

**Comment by adampl** [comment]
Maybe I was building the image in a wrong context. I will check it once it's merged. Thanks :)

**Comment by smuth4** [comment]
That PR only adds documentation, it doesn't change anything about the build itself.

**Comment by adampl** [comment]
Ah, sorry, you're right xD

**Pull request merged**
