### PR TITLE
Add 'pid' label to the perBrickLabels

### PR DESCRIPTION
**Pull request by VLZZZ**
This PR adds additional unique brick PID label to a metrics, which helps to ensure that we'll get consistent data when there's a volume containing several bricks which are running on the same peers.

Fixes the #175 

image

### CODE REVIEW

**Comment by VLZZZ** [comment]
@aravindavk I've noticed #173 and decided to add path as well, how do you think, will it be useful?

**Comment by VLZZZ** [comment]
@aravindavk Thanks
Maybe this will help with the CI issue - https://github.com/golangci/golangci-lint/issues/658#issuecomment-528126696

**Comment by aravindavk** [comment]
@VLZZZ Thanks, will look into this by this week.

**Comment by aravindavk** [comment]
> Maybe this will help with the CI issue - golangci/golangci-lint#658 (comment)

Looks like upgrading to latest version of golangci helped. I will retrigger this PR

**Comment by aravindavk** [comment]
@VLZZZ retriggering is still taking old travis file. Is it possible to rebase and push the patch again?

**Comment by VLZZZ** [comment]
@aravindavk Done
Thank you!

**Pull request merged**
